global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'bookstore-api'
      static_configs:
        - targets: ['188.245.77.152:8080']
      metrics_path: '/metrics'

    - job_name: 'conduit-backend'
      static_configs:
        - targets: ['188.245.77.152:5000']
      metrics_path: '/metrics'
